### ISSUE TITLE
Failed to wait for cert-rotator caches to sync in non-leader elected instances

### ISSUE THREAD

**Issue by astefanutti** [open-policy-agent/cert-controller#165]
In the case the cert controller is added to a non-leader manager, i.e., with `CertRotator.RequireLeaderElection` set to false, it fails with the following error message:

```
{"level":"error","ts":"2023-12-12T18:04:44.726776367Z","caller":"controller/controller.go:203","msg":"Could not wait for Cache to sync","controller":"cert-rotator","error":"failed to wait for cert-rotator caches to sync: timed out waiting for cache to be synced for Kind *v1.Secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:203\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:208\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:234\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/manager/runnable_group.go:223"}
```

**Comment by alculquicondor** [comment]
Side question:
Is this a regression?
Would it take long to produce a release or cert-controller? In that case, perhaps we can revert to an older version for a bit.

**Comment by astefanutti** [comment]
> Side question: Is this a regression?

Quickly looking at the history, I don't see any obvious reasons that would indicate it's a regression, but that would require more scrutiny.

> Would it take long to produce a release of cert-controller? In that case, perhaps we can revert to an older version for a bit.

Once the PR is approved and merged, we can temporary depend on the repo HEAD, only for the interim a new version is released.
