### ISSUE TITLE
Allow cert-controller to restart if a secret was changed

### ISSUE THREAD

**Issue by adrianludwin** [open-policy-agent/cert-controller#2]
We made this change in HNC's version of cert-controller and it reduced the initial startup time from >100s to about 10s. See https://github.com/kubernetes-sigs/multi-tenancy/commit/b070055945a118c88fcbcf2dfc09b1432885b94b.

I'd like to make the same change here - if the `--cert-restart-on-secret-refresh` flag is set (name is negotiable), then cert-controller will call `os.Exit()` when it updates a secret. This should only happen after initial installation or every 10y.

@maxsmythe , @ritazh , any thoughts on this?

**Comment by maxsmythe** [comment]
This would solve the bug we are seeing where the webhook randomly goes hard-down. OTOH it would re-add the behavior that the controller restarts once on bootstrapping that I know has been criticized in the past.

Personally, I'm for it. I'll take an aesthetic nit over crashing/complexity any day.

**Comment by ritazh** [comment]
+1
