### ISSUE TITLE
Create a new release that supports K8s 1.22+

### ISSUE THREAD

**Issue by adrianludwin** [open-policy-agent/cert-controller#40]
/cc @maxsmythe 
/cc @ritazh 

Hey Max + Rita, I see that we've recently gotten rid of the pre-v1 APIs we were using to access CRDs (I'd forgotten that we weren't on v1 yet). Does it make sense to cut a v0.3.0 release so there's a stable tag for this repo that supports K8s 1.22+?

Thanks!

**Comment by sozercan** [comment]
+1 on v0.3.0 tag and we should create release branches for existing ones

**Comment by maxsmythe** [comment]
+1

**Comment by sozercan** [comment]
Created v0.3.0 tag and release: https://github.com/open-policy-agent/cert-controller/releases/tag/v0.3.0

and release branches for v0.1, v0.2, and v0.3 in case we need to patch

**Comment by adrianludwin** [comment]
Thanks for doing this!
