### ISSUE TITLE
Support multiple dnsNames

### ISSUE THREAD

**Issue by JorTurFer** [open-policy-agent/cert-controller#51]
In [KEDA](https://keda.sh/) we are integrating this solution as a "default not safe" for cert management. Our problem is that we have 3 different components, the admission webhooks, the operator and the metrics server and all of them should share the certs because we want to use them for some internal communications.
Using cert-manager or other solution, we can just create a certificate with multiple dns names and sharing the same secret, we can secure all the internal communications and also webhooks and api services, but for new adopters, the requirement of a 3rd party could be a problem, and that's why we want to introduce this project for certificate management in non-productive environments, but not having the option for setting multiple dns names block us.

I'll open a PR with the changes in case you think this is useful

**Comment by JorTurFer** [comment]
Thanks for merging this! Just to plan the changes in KEDA, when will you release it? (no rush at all)

**Comment by maxsmythe** [comment]
TBH I don't think there is a strict release policy for this repo. Would cutting a new version help you?

**Comment by JorTurFer** [comment]
yeah! I used my own fork until the changes are released, if you release another version I can remove the `replace` from my go.mod xD

**Comment by ritazh** [comment]
Here you go https://github.com/open-policy-agent/cert-controller/releases/tag/v0.6.0
