### ISSUE TITLE
Add support for the Gatekeeper External Data Provider

### ISSUE THREAD

**Issue by bdun1013** [open-policy-agent/cert-controller#54]
The [Gatekeeper External Data Provider](https://open-policy-agent.github.io/gatekeeper/website/docs/externaldata/#provider), like the other supported Webhook types, requires the `caBundle` for the server.

**Comment by maxsmythe** [comment]
I'm not sure what this is asking for? Are you looking to use this library in an external data provider? Or are you looking to use this in some other way?

**Comment by bdun1013** [comment]
@maxsmythe Sorry for the lack on initial clarification. Yeah, the intention would be to allow this library to be used in an external data provider, potentially in the [cosign-gatekeeper-provider](https://github.com/sigstore/cosign-gatekeeper-provider) as part of https://github.com/sigstore/cosign-gatekeeper-provider/issues/20
